project:
  type: website
  resources:
    - inputs/
    - outputs/
    - templates-quarto/
website:
  title: "Intoduction to R framework at IMPACT Initiatives"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Cleaning - Checking a dataset"
        contents:
          - 01-cleaning/01-cleaning-01-checks.qmd
          - 01-cleaning/01-cleaning-02-add-duration-others.qmd
          - 01-cleaning/01-cleaning-03-logical-with-lists.qmd
          - 01-cleaning/01-cleaning-04-practice.qmd
      - section: "Cleaning - Creating a clean dataset"
        contents:
          - 02-cleaning/02-cleaning-01-create-cleaning-log.qmd
          - 02-cleaning/02-cleaning-02-create-clean-dataset.qmd
          - 02-cleaning/02-cleaning-03-review-cleaning.qmd
          - 02-cleaning/02-cleaning-04-practice.qmd
          - 02-cleaning/02-cleaning-05-extra.qmd
      - section: "Composition - Adding indicators"
        contents:
          - 03-composition/03-composition-01-add.qmd
          - 03-composition/03-composition-02-review.qmd
          - 03-composition/03-composition-03-practice.qmd
          - 03-composition/03-composition-04-extra.qmd
      - section: "Analysis - Simple analysis"
        contents:
          - 04-analysis/04-analysis-01-create-analysis.qmd
          - 04-analysis/04-analysis-02-practice.qmd
      - section: "Analysis - Extended analysis"
        contents:
          - 05-analysis-extended/05-analysis-01-loa.qmd
          - 05-analysis-extended/05-analysis-02-ratio.qmd
          - 05-analysis-extended/05-analysis-03-practice.qmd
      - section: "Analysis - Reviewing an analysis"
        contents:
          - 06-analysis-review/06-analysis-01-review.qmd
          - 06-analysis-review/06-analysis-02-practice.qmd
          - 06-analysis-review/06-analysis-03-extra.qmd
      - section: "Outputs - part 1"
        contents:
          - 07-outputs-part1/07-outputs-01-labels.qmd
          - 07-outputs-part1/07-outputs-02-tables.qmd
          - 07-outputs-part1/07-outputs-03-practice.qmd
      - section: "Outputs - part 2"
        contents:
          - 08-outputs-part2/08-outputs-01-ggplot-theme.qmd
          - 08-outputs-part2/08-outputs-02-tables-for-maps.qmd
          - 08-outputs-part2/08-outputs-03-tabular-html.qmd
          - 08-outputs-part2/08-outputs-04-practice.qmd
  repo-url: https://github.com/impact-initiatives/R-framework-with-IMPACT---how-to-use-the-tools
  repo-actions: [edit, source, issue]
format:
  html:
    toc: true
    code-link: true
    theme:
      - simplex
      - config/custom.scss
    df-print: kable
    embed-resources: true

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: es
    text: "Español"
  - name: fr
    text: "Francais"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es', 'fr']
title-es: Intoducciòn al Marco R en IMPACT Initiatives
title-fr: Introduction au cadre R chez IMPACT Initiatives
description-es: description in es
description-fr: description in fr
author-es: author in es
author-fr: author in fr
lang: en
